<a href="https://colab.research.google.com/github/euna-jeong20/ML/blob/main/01_03numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print('array1의 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2의 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3의 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1의 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2의 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3의 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [ ]:
#리스트 -> numpy array 할 수 있다.

list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* 리스트는 서로 다른 데이터 타입을 가질 수 있지만 ndarray내는 (연산을 위해)같은 데이터 타입만 가능하다.

* 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int, array_int.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int64


In [ ]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
seq_array = np.arange(100, 105)
seq_array

array([100, 101, 102, 103, 104])

In [ ]:
seq_array = np.arange(707, 1000, 100)
seq_array

array([707, 807, 907])

In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)
print(array1.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
array2 = array1.reshape(2,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array3 = array1.reshape(10,1)
array3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
array4 = array1.reshape(1, 10)
array4

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(-1,5)
#print('array2 : \n',array2)
print('array2 shape :', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape :', array3.shape)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape : (5, 2)


In [ ]:
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2)
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#인덱싱

In [ ]:
arr = np.arange(start=1, stop=10)
print('arr :', arr)

val = arr[2]
print('value : ', val, ',type: ',type(val))

print('맨 뒤의 값:', arr[-1], ', 맨 뒤에서 두 번째 값 : ', arr[-2])

arr : [1 2 3 4 5 6 7 8 9]
value :  3 ,type:  <class 'numpy.int64'>
맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값 :  8


In [ ]:
#ndarray 값 수정
arr[0] = 9
arr[8] = 0
print('arr : ', arr)

arr :  [9 2 3 4 5 6 7 8 0]


In [ ]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)
print(arr2d)

print('(row=0, col=0) index 가리키는 값:', arr2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', arr2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', arr2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', arr2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#슬라이싱

In [ ]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]

print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.arange(start=1, stop=10)
arr4 = arr1[:3]
print(arr4)

arr5 = arr1[3:]
print(arr5)

arr6 = arr1[:]
print(arr6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
print('arr2d: \n', arr2d)

print('arr2d[0:2, 0:2] \n', arr2d[0:2, 0:2])
print('arr2d[1:3, :] \n', arr2d[1:3, :])
print('arr2d[:, :]\n', arr2d[:, :])
print('arr2d[:2, 0] \n', arr2d[:2, 0])

arr2d: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 0] 
 [1 4]


In [ ]:
print(arr2d[0])
print(arr2d[0].shape)

[1 2 3]
(3,)


In [ ]:
print(arr2d[1])
print(arr2d[1].shape)

[4 5 6]
(3,)


# 팬시 인덱싱

In [ ]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
print('arr2d : \n', arr2d)

arr3 = arr2d[[0,1], 2]
print(arr3)

arr2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]


In [ ]:
arr4 = arr2d[[0,2], 1]
print(arr4)

[2 8]


In [ ]:
arr5 = arr2d[[0, 1]]
print(arr5)

[[1 2 3]
 [4 5 6]]


# 불린 인덱싱

In [ ]:
arr1d = np.arange(start=1, stop=10)
arr3 = arr1d[arr1d > 5]
arr3

array([6, 7, 8, 9])

In [ ]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
arr4 = arr1d[boolean_indexes]
arr4

array([6, 7, 8, 9])

In [ ]:
indexes = np.array([5, 6, 7, 8])
arr5 = arr1d[indexes]
arr5

array([6, 7, 8, 9])

#행렬의 정렬

In [ ]:
org = np.array([3, 1, 9, 5])
print('원본 : ', org)

#np.sort()로 정렬
sort1 = np.sort(org)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort1)
print('np.sort() 호출 후 원본 행렬 : ', org)

#ndarray.sort()로 정렬
sort2 = org.sort()
print('org.sort() 호출 후 반환된 행렬 : ', sort2)
print('org.sort() 호출 후 원본 행렬 : ', org)

원본 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org.sort() 호출 후 반환된 행렬 :  None
org.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [ ]:
#기본이 오름차순이지만 내림차순으로 정렬하는 방법

sort_dec = np.sort(org)[::-1]
print('내림차순으로 정렬 : ', sort_dec)

내림차순으로 정렬 :  [9 5 3 1]


In [ ]:
arr2d = np.array([[8, 12],
                  [7, 1]])

sort_axis0 = np.sort(arr2d, axis=0)
print('로우 방향으로 정렬 : \n', sort_axis0)

sort_axis1 = np.sort(arr2d, axis=1)
print('칼럼 방향으로 정렬 : \n', sort_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [ ]:
#np.argsort()를 이용해 원본 행렬의 정렬시 행렬 인덱스
org = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org)

print(type(sort_indices))
print('원본 행렬의 정렬시 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 바뀐 인덱스 :  [1 0 3 2]


In [ ]:
org = np.array([3, 1, 9, 5])
sort_indices_dec = np.argsort(org)[::-1]
print('원본 행렬의 내림차순 정렬시 인덱스 : ', sort_indices_dec)

원본 행렬의 내림차순 정렬시 인덱스 :  [2 3 0 1]


In [ ]:
#응용

name_arr = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_arr = np.array([78, 95,84, 98, 88])

sort_indices_asc = np.argsort(score_arr)
print('성적 오름차순 정렬 시 score_arr의 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_arr의 이름 출력', name_arr[sort_indices_asc])

성적 오름차순 정렬 시 score_arr의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_arr의 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 행렬 내적과 전치 행렬 구하기

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

np.transpose(A)

array([[1, 3],
       [2, 4]])